export const listEmployees = [

  {
    id: 1,
    name: "Olivia Rhye",
    code: "#465462",
    phone: "0947211201",
    region: "Bình tân",
    role: "Nhân viên",
    email: "abe@gmail.com",
    status: "Đang hoạt động",
  },
  {
    id: 2,
    name: "Phoenix Baker",
    code: "#465462",
    phone: "0947211201",
    region: "Bình tân",
    role: "Giám sát",
    email: "abe@gmail.com",
    status: "Chưa kích hoạt",
  },
  {
    id: 3,
    name: "Lana Steiner",
    code: "#465462",
    phone: "0947211201",
    region: "Bình tân",
    role: "Giám sát",
    email: "abe@gmail.com",
    status: "Đã khóa tài khoản",
  },
  {
    id: 4,
    name: "Demi Wilkinson",
    code: "#465462",
    phone: "0947211201",
    region: "Bình tân",
    role: "Nhân viên",
    email: "abe@gmail.com",
    status: "Đang hoạt động",
  },
  {
    id: 5,
    name: "Candice Wu",
    code: "#465462",
    phone: "0947211201",
    region: "Bình tân",
    role: "Giám sát",
    email: "abe@gmail.com",
    status: "Chưa kích hoạt",
  },
  {
    id: 6,
    name: "Alex",
    code: "#465462",
    phone: "0947211201",
    region: "Bình tân",
    role: "Giám sát",
    email: "abe@gmail.com",
    status: "Đã khóa tài khoản",
  },
  {
    id: 7,
    name: "Jame",
    code: "#465462",
    phone: "0947211201",
    region: "Bình tân",
    role: "Nhân viên",
    email: "abe@gmail.com",
    status: "Đang hoạt động",
  },
  {
    id: 8,
    name: "Herry",
    code: "#465462",
    phone: "0947211201",
    region: "Bình tân",
    role: "Giám sát",
    email: "abe@gmail.com",
    status: "Chưa kích hoạt",
  },
  {
    id: 9,
    name: "Philip",
    code: "#465462",
    phone: "0947211201",
    region: "Bình tân",
    role: "Giám sát",
    email: "abe@gmail.com",
    status: "Đã khóa tài khoản",
  },

]